### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by Shinyzenith** [swaywm/zig-wlroots#42]
Hi, I'm trying to write a compositor in zig and it would be really useful if tinywl.zig could have some comments to explain the intricate parts.

**Comment by ifreund** [comment]
I'd recommend reading the comments in `tinywl.c` instead: https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/tinywl/tinywl.c

I didn't take the time to port these comments over and don't have any plans to in the short term. If you have any questions specific to the zig version feel free to ask on IRC, may be worth adding some comments on the minor things that differ (are there really any? I don't recall).

The same goes for the wlroots bindings themselves, the real documentation lives in the wlroots C headers and source code.

**Comment by Shinyzenith** [comment]
A question popped up while writing my compositor. I don't know the name of the irc room, is it okay if I send a private message request on matrix?

**Comment by novakne** [comment]
There is \#river on libera, \#sway-devel also on libera, for wlroots development, and \#wayland on OFTC.

**Comment by Shinyzenith** [comment]
Is it possible to make a river room over on matrix? irc constantly removing old messages is an inconvenience for sure.

**Comment by Leon-Plickat** [comment]
We have IRC logs at https://libera.irclog.whitequark.org/river/2022-03-13

And if anything comes up that should be persistent, it can be added to the wiki / the docs. Chat logs are a super terrible way to store and find any kind important information.

**Comment by tiosgz** [comment]
> Is it possible to make a river room over on matrix?

The irc room is bridged over to `#river:libera.chat`
