### ISSUE TITLE
render.renderer.Renderer.getDmabufFormats() can return null

### ISSUE THREAD

**Issue by RossComputerGuy** [swaywm/zig-wlroots#60]
Tried testing a custom compositor which calls the method `render.renderer.getDmabufFormats()` (`wlr_renderer_get_dmabuf_texture_formats`) with `WLR_RENDERER=pixman` and that causes `getDmabufFormats` to return `null` but `render.drm_format_set.DrmFormatSet` cannot be used if it is `null`.

**Comment by ifreund** [comment]
Fixed in d6c070a, thanks.
