### ISSUE TITLE
Incorrect parent type on scene_node struct

### ISSUE THREAD

**Issue by Shinyzenith** [swaywm/zig-wlroots#67]
For wlroots 0.16.0

zig-wlroots has the following binding for wlr_scene_node->parent: https://github.com/swaywm/zig-wlroots/blob/master/src/types/scene.zig#L19

Wlroots has the following type signature:
https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/1712a7d27444d62f8da8eeedf0840b386a810e96/include/wlr/types/wlr_scene.h#L50

**Comment by ifreund** [comment]
Yep, feel free to send a patch!

**Comment by Shinyzenith** [comment]
Working on one.
