### ISSUE TITLE
req: wlroots 0.17 compatibility

### ISSUE THREAD

**Issue by nergdron** [swaywm/zig-wlroots#69]
new wlroots has some vulkan rendering features I'd really like, so I'd love to see this updated with compatibility for that integrated. 💚

**Comment by ifreund** [comment]
It will be updated as soon as I have time to do so as has always been the case for new wlroots releases. There also happens to be a PR I have not yet reviewed that updates to a relatively recent wlroots master version if that's useful to you: https://github.com/swaywm/zig-wlroots/pull/64

In any case, there's no need to have an issue open to track this.

**Comment by nergdron** [comment]
oh great, thanks!
